version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest

  build:
    commands:
      - echo "Building the project..."
      - aws s3 cp . s3://demowebsite-kt --recursive

artifacts:
  files:
    - '**/*'
